main:main.c
	@gcc -o main main.c

errone:errone.c
	gcc -o errone errone.c

errtwo:errtwo.c
	@gcc -o errtwo errtwo.c

errthr:errthr.c
	gcc -o errthr errthr.c

errfou:errfou.c
	gcc -o errfou errfou.c

clean:
	@rm -f main errone errtwo errfou errthr *.o 

